### ISSUE TITLE
GCP Ubuntu PRO: `ua enable fips` leaves FIPS reboot notice intact across reboot.

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-pro-client#1499] opened 2021-03-31 02:47 UTC
`ua enable fips` on an Ubuntu PRO machine will add the following notice to `ua status` output because ubuntu-fips package marks touches `/var/lib/ubuntu-advantage/marker-reboot-cmds-required` which `ua enable fips` checks prior to emitting this notice.

```bash
NOTICES
FIPS support requires system reboot to complete configuration.
```

This notice should be cleared across reboot by ua-reboot-cmds.service but it is not. It doesn't appear that ua-reboot-cmds is run at all, whch means `ua enable fips` never calls cfg.write_cache("reboot-cmds"marker", "") to enqueue ua-reboot-cmds.service in systemd during next boot.

non-root users will continue to see this notice even after system reboot into an active fips kernel.
root users running `ua status` will properly refresh FIPS status and clear this notice.

**Comment by blackboxsw** [comment] 2021-03-31 02:48
This is minor, but will affect all ubuntu-pro images w/ 26.2 or later until a fix is released

**Comment by lucasmoura** [comment] 2021-03-31 20:47
@blackboxsw After debugging this issue, I have find out that error is caused by running `ua status` as non-root after the reboot. This happens because when we run `ua status`  as non-root we just get the output directly from the cache:
https://github.com/canonical/ubuntu-advantage-client/blob/master/uaclient/config.py#L530

If we run the command as sudo we will see that the notices are indeed removed.
This seems as a another good argument to run `ua status` in the background after a reboot operation happens

**Comment by orndorffgrant** [comment] 2022-02-02 14:17
This will be fixed with SC-708, which will make non-root `ua status` show up-to-date info always

**Comment by lucasmoura** [comment] 2023-10-16 18:27
I can confirm this no longer affects the Pro client due to the `pro status` refactor for better handling non-root users

**Closed by lucasmoura** 2023-10-16 18:27 UTC
Labels: triaged
