### ISSUE TITLE
Question:  Ubuntu Pro wont register

### ISSUE THREAD

**Issue by jwaltrip4** [canonical/ubuntu-pro-client#2786] opened 2023-10-11 17:30 UTC
It was prviously enabled.   I wnet to enable another service (livepatch) and it resonded that it was not enabled

I disabled and enableed.  Error message:

***Failed to connect to authentication server
Check your Internet connection and try again.***

I have tried uninstalling and purging, and reinstalled and that has not helped.

Any thoughts on what to do next?

 - [X] There is no documentation about this

**Comment by orndorffgrant** [comment] 2023-10-11 19:59
Thanks for the bug report @jwaltrip4!

This is related to #2647

It's hard to tell exactly what happened from this description and error message. Can you run `sudo pro collect-logs` and attach the tarfile it creates to a new comment on this issue?

**Comment by jwaltrip4** [comment] 2023-10-11 20:31
Gladly

[ua_logs.tar.gz](https://github.com/canonical/ubuntu-pro-client/files/12874346/ua_logs.tar.gz)

**Comment by orndorffgrant** [comment] 2023-10-11 20:45
Thanks! From taking a look at the logs, the underlying error is `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)`.

Pro client uses the system openssl configuration, so an SSL error is usually a signal that something isn't working at that level (as opposed to something wrong with `pro`). What happens when you run `curl https://contracts.canonical.com/v1/resources` or `wget https://contracts.canonical.com/v1/resources`? Do you get a similar SSL error?

**Comment by jwaltrip4** [comment] 2023-10-11 21:07
Not sure how to read...

[curl.txt](https://github.com/canonical/ubuntu-pro-client/files/12874578/curl.txt)
[resources-wget.txt](https://github.com/canonical/ubuntu-pro-client/files/12874580/resources-wget.txt)

**Comment by jwaltrip4** [comment] 2023-10-11 21:08
OpenSSL 1.1.1u  30 May 2023

**Comment by orndorffgrant** [comment] 2023-10-12 19:12
Interesting, that is successful output for both commands, but I expected those to fail with a similar SSL error. Can you try the following and let me know what they do?

```
python3 -c 'from urllib import request; print(request.urlopen("https://contracts.canonical.com/v1/resources").read().decode())'
```
```
python3 -c 'from uaclient import http; print(http.readurl("https://contracts.canonical.com/v1/resources"))'
```
```
echo | openssl s_client -connect contracts.canonical.com:443
```

If none of those fail, then I'll be extra surprised :upside_down_face:

**Comment by jwaltrip4** [comment] 2023-10-12 19:29
[echo.txt](https://github.com/canonical/ubuntu-pro-client/files/12886445/echo.txt)
[uaclient.txt](https://github.com/canonical/ubuntu-pro-client/files/12886446/uaclient.txt)
[urlib.txt](https://github.com/canonical/ubuntu-pro-client/files/12886451/urlib.txt)

**Comment by orndorffgrant** [comment] 2023-10-12 19:38
Thanks @jwaltrip4! This confirms that the problem is happening outside of pro-client and is an issue with openssl configuration/trusted certificates on the system.

Some things to check:
- make sure your certs are up to date: `sudo apt update && sudo apt install ca-certificates`
- make sure the ISRG_Root_X1.crt cert is trusted. You can reconfigure which certs are trusted with `dpkg-reconfigure ca-certificates`

Other than that, this falls outside of pro-client so I'm going to close the issue here. You may find more help on AskUbuntu or StackOverflow if you post the output of the `echo | openssl s_client -connect contracts.canonical.com:443` command and describe the situation.

I hope this helps.

**Closed by orndorffgrant** 2023-10-12 19:38 UTC

**Comment by jwaltrip4** [comment] 2023-10-12 20:09
meh.... going to reinstall the server.  spent enough time today to have done that.
thanks
