### ISSUE TITLE
Bug: service status dependency on apt-cache can lead to incorrect/misleading service status

### ISSUE THREAD

**Issue by Monochromics** [canonical/ubuntu-pro-client#2801] opened 2023-10-18 19:19 UTC
This might be more of an opinion than a true bug, so feel free to close if the current implementation is required

**Description of the bug**

It appears that the repo status is driven in some part by apt-cache, which can be problematic if someone/something is cleaning /var/lib/apt/lists/*. If you enable esm-infra, remove the esm entries from /v/l/a/lists/, then run `pro status` again, the services will report as disabled.

I'm not sure why this would be done, (and apt-get clean does not remove the lists themselves), however I have seen at least one instance of this recently. 

It seems like status should be driven more by the capability of getting esm packages rather than a check against the versioning itself.

**Expected behavior**
Service status would report `enabled` if the repositories were present in sources.list.d, credentials were present in auth.conf.d, and apt-helper or another tool could successfully reach the repository. If we do want to keep it this way, perhaps there should be an `apt update` exec prior to outputting status? There have been recent issues regarding trimming `apt update` runs, so this may not be ideal for speed of execution.

**Current behavior**

Service status is (to my understanding) driven by apt-cache, which relies on the presence of the esm metadata in /v/l/a/lists/, rather than the service actually being enabled

**To Reproduce**

1. Launch a VM/Container
2. Attach pro w/ esm-infra (or other) enabled
3. Confirm enablement with `pro status`
4. Remove *esm* from /var/lib/apt/lists/
5. Exec `pro status` and observe esm-infra being marked as disabled.

**System information:**

- Ubuntu release: 22.04/20.04 (but presumably all releases)
- Pro Client version: 29.4~20.04 (on focal test inst)

**Additional context**

As mentioned at the start, my suggested behavior has it's own set of drawbacks. Considering there footprint of people bothering to clean /v/l/a/lists outside of apt's auto-management, this may not be worth the effort. Primarily just wanted to raise this if it was not a known `issue`

**Comment by lucasmoura** [comment] 2023-10-24 15:29
Thanks for reporting this @Monochromics. The problem is that we currently parse the output of `apt-cache policy` to assert if some services are enabled or not. If any operation affects that, we might incorrectly say that the service is disabled as can be seen on the scenario you described.

We are already planning on modifying that logic to not rely on ` apt-cache policy` anymore and this issue reinforces this need

**Comment by orndorffgrant** [comment] 2024-10-23 18:59
@lucasmoura did look into this a year ago and it ended up being more complicated than expected to remove this dependency and still be sure that APT was correctly configured before saying "enabled".
I'm going to go ahead and close this as a "Won't Fix" for now, but acknowledge that the problem described still exists. If you see this more often or this becomes important, feel free to re-open.

**Closed by orndorffgrant** 2024-10-23 18:59 UTC
Labels: bug, triaged
