### ISSUE TITLE
enable livepatch fails when already previously used

### ISSUE THREAD

**Issue by basak** [canonical/ubuntu-pro-client#1570] opened 2021-04-26 12:44 UTC
I'm sorry, I completely failed to save the output, so this is from memory just now.

I upgraded to `ubuntu-advantage-tools 27.0~16.04.1~beta3` from the staging PPA to test on a Xenial machine where I've previously played with livepatch. After attaching, `ua status` said that livepatch was disabled, so I tried `ua enable livepatch`. This failed with a message that told me that a machine token already existed and that I should try `disable` first. `ua disable livepatch` didn't work, and then I realised that the message was actually from `canonical-livepatch` so I ran `canonical-livepatch disable` which seemed to do something. After that, `ua enable livepatch` worked.

So I'm fine now, but I hope this is useful feedback. I suppose I'd expect `ua enable livepatch` to be able to figure this case out, but I'll leave it to you to decide how it should behave :)

**Comment by mitechie** [comment] 2021-04-26 12:53
Thanks, we'll double-check our testing scenarios with existing livepatch installations.

**Comment by blackboxsw** [comment] 2021-04-26 16:38
Thanks @basak for filing this. I'm uncertain if you previously played with livepatch in UA client? or not, but here are is the expected behavior which I just verified.

A system with canonical-livepatch installed from the ubuntu-advantage-tools=10ubuntu0.16 from xenial-updates via  `ubuntu-advantage enable-livepatch <livepatch_token>`, upgrade to ubuntu-advantage-tools 27~beta3.
`ua status` will show the system as unattached:
```bash
SERVICE     AVAILABLE    DESCRIPTION
...
livepatch       yes                 Canonical Livepatch service

This machine is not attached to a UA subscription
See https://ubuntu.com/advantage
```

After attaching:
```bash
sudo ua attach <MY_TOKEN>
....
SERVICE      ENTITLED     STATUS       DESCRIPTION
....
livepatch        yes                 enabled        Canonical Livepatch servie
...
```


I also validated that there is a minor regression in that the `ua attach` which incorrectly disables livepatch on contract attach, https://github.com/canonical/ubuntu-advantage-client/issues/1571. Will sort that separately than this issue.

**Comment by basak** [comment] 2021-04-26 17:14
I played with livepatch in the past directly, without UA client. It's
possible that I had disabled it somehow - eg. by removing the snap. This
seems likely from my canonical-livepatch refresh-date.

Maybe this will reproduce:

sudo snap install canonical-livepatch
sudo canonical-livepatch enable
sudo snap remove canonical-livepatch
<install ua client from beta>
sudo ua attach ...
sudo ua enable livepatch

**Comment by orndorffgrant** [comment] 2022-01-05 14:14
Tracking in SC-707

**Comment by orndorffgrant** [comment] 2023-05-30 20:58
Our integration with livepatch has improved since this issue was opened, and I'm unable to reproduce this problem by using `canonical-livepatch enable` prior to a `pro attach` so I'm closing it. Please re-open if you run can reproduce this.

**Closed by orndorffgrant** 2023-05-30 20:58 UTC
Labels: beta-feedback, triaged
